### PR TITLE
snippet(latex): Add `(texmathp)` condition to certain snippets

### PR DESCRIPTION
**Pull request by itxprashant**
Fix: #c63094b
- Added `(texmathp)` condition for math specific snippets.
- Added `yasnippet-mode` header for int, sum and prod.
- Removed file-ending newlines.

### CODE REVIEW

**Comment by itxprashant** [comment]
Kindly merge this commit and delete the previous one, because it introduced some new-lines bug.

**Comment by hlissner** [comment]
Thanks again!

**Comment by itxprashant** [comment]
Don't want to bother you, but the newlines omission hasn't been merged yet, that's why I intended for deletion of previous commit and rebasing this one.

**Comment by hlissner** [comment]
Ah, my bad! I don't generally like to force-push on commits that are more than 30 minutes old, so rather than delete the old commit, I've overwritten [ed571b1](https://github.com/doomemacs/snippets/commit/ed571b1fabe5b7c90ea89e9b572fb13988ffe46c) with [cacd22f](https://github.com/doomemacs/snippets/commit/cacd22f8d5ad0bdbc4e6e4502d90650e74f91a26), which includes the newlines fix (and a more correct commit message). Thanks for letting me know, in any case!

**Comment by itxprashant** [comment]
Thank you so much!

**Pull request merged**
